### ISSUE TITLE
drop `gh-pages`

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/yadism#159]
unfortunately, I only realize after releasing that https://github.com/NNPDF/yadism/commit/b88c280d31373bb85b9e408a2d55765d4fba8051 fixes the link so it still points to `gh-pages` - which is hopelessly outdated. The official documentation is now at https://yadism.readthedocs.io/en/latest/ (which also could provide former version if we configure correctly - see eko). Should I re-release, @AleCandido ? then we should drop `gh-pages` completely for the moment to avoid confusion ... if ever, in a far future, we could use `gh-pages` (as in eko) to provide backup material, plots, etc.

cc @scarlehoff

**Comment by scarlehoff** [comment]
As a landing page the github you have is nice though (I didn't realise the links to the docs were not pointing to readthedocs though)

**Comment by AleCandido** [comment]
> As a landing page the github you have is nice though (I didn't realise the links to the docs were not pointing to readthedocs though)

Nah, not so great... I was young and not so skilled (and still I'm not, but slightly better than before...(
