### ISSUE TITLE
FONLL-B below charm mass is NNLO instead of NLO

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/yadism#165]
thanks to @scarlehoff I realized we have a bug in the FONLL-B implementation if $Q^2 < m_c^2$.

In this regime there is no FONLL prescription, but instead we should fall back to an ordinary 3FFNS scheme in __NLO__.

The bug is: we are falling back into an 3FFNS at __NNLO__ - that is one order too high. Since this regime never enters the fit this bug leaves NNPDF unaffected.

this can be seen here: using https://github.com/NNPDF/theories/blob/main/data/grids/400/HERA_NC_300GEV_EP_SIGMARED.pineappl.lz4 and https://github.com/NNPDF/theories/blob/main/data/grids/405/HERA_NC_300GEV_EP_SIGMARED.pineappl.lz4 we get
```
$ pineappl diff 400-HERA_NC_300GEV_EP_SIGMARED.pineappl.lz4 405-HERA_NC_300GEV_EP_SIGMARED.pineappl.lz4 toyantichsing
LHAPDF 6.4.0 loading /home/felix/local/share/LHAPDF/toyantichsing/toyantichsing_0000.dat
toyantichsing PDF set, member #0, version 1
 b      x1                x2                       O(as^0 a^0)                         O(as^1 a^0)                           O(as^2 a^0)             
---+-----+-----+-----------+-----------+------------+------------+-------+--------------+--------------+-------+-------------+-------------+---------
[...]
 37     2     2   0.0000327   0.0000327 1.6319161e-6 1.6319161e-6 0.000e0  -7.2723743e-8  -7.2723743e-8 0.000e0  3.2375257e-3  3.2375257e-3   0.000e0
 38     2     2     0.00005     0.00005 1.5643400e-6 1.5643400e-6 0.000e0  -3.5992462e-8  -3.5992462e-8 0.000e0  7.1254621e-5  7.1254621e-5   0.000e0
 39   2.7   2.7   0.0000409   0.0000409 2.1573936e-6 2.1573936e-6 0.000e0  -1.0207650e-7  -1.0207650e-7 0.000e0  1.0839735e-2  1.6568186e-3   5.542e0
```

I'm not 100% sure how this happened

**Comment by AleCandido** [comment]
It is not a bug, it is the expected behavior: FONLL-B is a NNLO scheme concerning quark masses treatment, so below charm mass it is fully NNLO.

**Comment by felixhekhorn** [comment]
Note that above I used `toyantichsing` which means that also the light part is at NNLO - that is the bug (agreed description is not precise enough)

**Comment by felixhekhorn** [comment]
close in favor of chat
