### ISSUE TITLE
Minus sign missing in k_qq_loc

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/yadism#176]
While trying to benchmarking `DIS_TP` I might have found a global minus sign missing in this function:

https://github.com/NNPDF/yadism/blob/e3eab124b25083c32289134c8204a8bf0f4b33b8/src/yadism/coefficient_functions/fonll/partonic_channel.py#L108

here you have a test checking the convolution of `K_qq` and a test function, both with Yadism and Eko:

```
import numpy as np
from scipy.integrate import quad
from eko.mellin import Path
from ekore.harmonics import compute_cache
from ekore.operator_matrix_elements.unpolarized.space_like import as2
from numpy.testing import assert_allclose


from yadism.coefficient_functions.fonll.partonic_channel import (
    PdfMatchingNNLLNonSinglet,
)
from test_pc_general import MockESF


nf = 4

# a simple test function and its mellin transform
def f(x):
    return 1

def mellin_f(n):
    return 1/(n)

# x-space convolution
def yad_convolute(x, q):
    esf = MockESF(x, q**2)
    match = PdfMatchingNNLLNonSinglet(esf, nf, m2hq=q**2).NNLO()
    loc = match.loc(x, match.args["loc"]) * f(x)
    sing = quad(
        lambda z: match.sing(z, match.args["sing"]) * (f(x / z) / z - f(x)),
        x,
        1,
    )[0]
    return sing + loc

# n-space convolution
def inverse_mellin(x):
    def quad_ker_talbot(u, func):
        path = Path(u, np.log(x), True)
        sx = compute_cache(path.n, 3, True)
        sx = [np.array(s) for s in sx]
        integrand = path.prefactor * x ** (-path.n) * path.jac
        gamma = func(path.n, sx, L=0) * mellin_f(path.n)
        return np.real(gamma * integrand)

    return quad(
        lambda u: quad_ker_talbot(u, as2.A_qq_ns),
        0.5,
        1.0,
        epsabs=1e-12,
        epsrel=1e-6,
        limit=200,
        full_output=1,
    )[0]


class Test_Matching_qq:
    xs = [0.0001, 0.001, 0.01, 0.1, 0.2, 0.456, 0.7]
    Qs = [5, 10, 20]

    def test_nnlo(self):
        my = []
        eko = []
        for q in self.Qs:
            for x in self.xs:
                my.append(yad_convolute(x, q))
                eko.append(inverse_mellin(x))
        assert_allclose(my, eko)
```
I was not able to provide a simpler test, because the local part of this function is singlular at `x=1`. 
You can verify that the test is passing only once a minus sign is added to `K_qq_loc` .
This minus sign would also be consistente with the comment inside the function which report the mathematica integration.

Thanks for having a look, maybe I'm not using the code correctly and the minus is somewhere else ?

**Comment by AleCandido** [comment]
I should have a closer look, but a minus sign might be expected: remember that the anomalous dimensions (following Pegasus or Vogt definition) or *minus* the Mellin inverse of the splitting functions.

**Comment by giacomomagni** [comment]
In matching condition mellin transform there should be no minus sign.
But if that is the case it should have appeared as a global minus sing not only on the local bit.
