### ISSUE TITLE
Light structure functions  à la FONLL

### ISSUE THREAD

**Issue by alecandido** [NNPDF/yadism#200]
The three definitions of light structure functions currently in use are:

1. `uds`, like APFEL 
    - but this makes sense up to a point, e.g. if you are computing bottom mass effects `udsc` would make more sense
2. ZM-VFNS, i.e. fully light
    - already available choosing the suitable `FNS` and matching scales
3. FONLL, i.e. light quarks coupling to the EW boson

At the moment, we provide 2., because to us made more sense than 1., but it would make more sense to either have 3. (`uds` in `nf=3`, `udsc` in `nf=4`, ...) or nothing at all, since even 3. would be mainly used to debug FONLL itself.

**Comment by giacomomagni** [comment]
We can close this as complete, as we now support numerical FONLL

**Comment by felixhekhorn** [comment]
agreed
