### ISSUE TITLE
Make a new release of yadism

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/yadism#300]
Required to bump the pineappl version of pinefarm (https://github.com/NNPDF/pinefarm/pull/81).

**Comment by giacomomagni** [comment]
Sorry for the delay, we need some minor fix for the fonll paper as well. 
here you have: https://github.com/NNPDF/yadism/releases/tag/v0.13.4

**Comment by Radonirinaunimi** [comment]
NP, it was more to keep track of the various missing pieces.

Thanks a lot!
